package src.scrabble.model;

/**
 * Represents a possible move generated by the AI player.
 * Stores word placement details and the computed score.
 *
 * @author Ashfaqul Alam, 101195158
 * @version Nov 23rd, Milestone 3
 */
class AIMove {
    public String word;
    public int row;
    public int col;
    public boolean horizontal;
    public int score;

    /**
     * Constructs an AI move suggestion.
     *
     * @param var1 the word the AI wants to place
     * @param var2 row index on the board (0-based)
     * @param var3 column index on the board (0-based)
     * @param var4 true if placed horizontally, false vertically
     * @param var5 computed score for this move
     */
    public AIMove(String var1, int var2, int var3, boolean var4, int var5) {
        this.word = var1;
        this.row = var2;
        this.col = var3;
        this.horizontal = var4;
        this.score = var5;
    }

    /**
     * Returns a readable summary of the move.
     *
     * @return formatted string describing word, coordinates, orientation, and score
     */
    @Override
    public String toString() {
        return this.word + " at (" + (this.row + 1) + "," + (this.col + 1) + ") " + (this.horizontal ? "H" : "V") + " - Score: " + this.score;
    }
}
